# Generated by Django 5.2.8 on 2026-03-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_instructor_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='lesson_description',
            field=models.TextField(blank=True, help_text='Description of lesson style, approach, and what students can expect'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='package_10_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='10 session package rate (total)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='package_5_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='5 session package rate (total)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='package_monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly unlimited package rate', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='package_single_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Single session rate', max_digits=6, null=True),
        ),
    ]
