# Generated by Django 5.2.8 on 2026-03-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_instructor_lesson_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="class_type",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Primary class type (e.g., Personal Trainer, "
                    "Yoga, Pilates, Boxercise)"
                ),
                max_length=100,
            ),
        ),
    ]
